### PR TITLE
Replace XMLHttpRequest to use unfetch

### PR DESCRIPTION
**Pull request by emmafallancy**
Hi @iaincollins 

Saw the issue that you made (#45) and I would like to give a hand on it. This PR is pretty much just replacing XMLHttpRequest to use `unfetch`. Let me know if this is good for you 😃

### CODE REVIEW

**Comment by iaincollins** [comment]
Oh this is awesome, thank you! \o/

**Comment by iaincollins** [comment]
It seems there is a problem fetching the session client side after logging in with this, so had to revert it for now, but am going to investigate and restore it once I've tracked down the bug.

**Comment by emmafallancy** [comment]
Ah! Sorry about that :( Didn't realised that it causes problem

**Comment by iaincollins** [comment]
Not at all, really appreciate it! It's a good reminder I need to write some tests. :)

**Comment by iaincollins** [comment]
Hey @emmafallancy just wanted to let you know your pull request has finally gone live :-)

In a minor change it actually uses fetch - technically isomorphic-fetch, but only because it was already included in the project for the async example.

It looks like unfetch didn't seem to work as I'd thought but it seems fine with fetch and `credentials: 'same-origin' option.

Sorry for the confusion and thanks for the pull request!

**Comment by emmafallancy** [comment]
@iaincollins Awesome! 🎉 Don't mind the PR before. Happy to hear that it works better and got to reduction of 20 LOC! 😄

**Pull request merged**
